sudo: required 
dist: focal 
language: generic
services:
  - docker
compiler:
  - gcc
notifications:
  #  Whoever receives success and/or failure via email
  email:
    recipients:
      - auvic@uvic.ca  # Change this to yours should you copy this file.
env:
  matrix:
    - ROS_DISTRO="noetic" ROS_REPO=ros DOCKER_BASE_IMAGE=ros:noetic-ros-core
    - ROS_DISTRO="noetic" ROS_REPO=ros-shadow-fixed DOCKER_BASE_IMAGE=ros:noetic-ros-core
    - ROS_DISTRO="noetic" PRERELEASE=true
matrix:
  allow_failures:
    - env: ROS_DISTRO="noetic" PRERELEASE=true
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config  
script: 
  - source .auvic_ci/travis.sh
